services:
  db:
    image: postgres:16
    container_name: db
    env_file:
      - .env
    environment:
      POSTGRES_DB: mtproto_db
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data


  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: web
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: ./deploy/nginx/Dockerfile.nginx
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/src/server/static/
      - media_volume:/app/src/server/media/
    depends_on:
      - web

volumes:
  pg_data:
  static_volume:
  media_volume: